### PR TITLE
Master Update

### PR DESCRIPTION
**Pull request by Justman10000**
What does this update?

- Localization (run the AdminTools site in as many languages ​​as you want)
- Fixed minor bugs

### CODE REVIEW

**Review by LukeOnuke — APPROVED** [review]

**Comment by LukeOnuke** [comment]
Thanks for the contribution!

**Comment by LukeOnuke** [comment]
Ive just got a question, how do i deploy it properly to github pages. Its just broken even when going to page `/public`

**Comment by Justman10000** [comment]
Since I have experience in this, I could also host the site... I would then always check the repository here for updates and then apply them...

**Comment by LukeOnuke** [comment]
Will see something

**Comment by Justman10000** [comment]
> Will see something

So, tomorrow the hoster will probably go online, where I'm the manager! You could get a small vServer there... I would then install everything on it...

**Comment by LukeOnuke** [comment]
Sorry for responding late, that is a great idea

**Comment by Justman10000** [comment]
> Sorry for responding late, that is a great idea

[Here](https://discord.gg/Juet6BgGz4) is the Link... Although we are a German hoster, we will also support English...

**Comment by LukeOnuke** [comment]
I know a little bit of german, so this evening ill se what i can do.

**Comment by Justman10000** [comment]
> ...I get a free small vps for future at apis...

Apis?

**Comment by Justman10000** [comment]
> May i recommend a sponsorship, I get a free small vps for future at apis and for the website and you get your companies banner in the admintools readme.md file. Does it sound good?

Would it also be possible to put our banner on the website?

**Comment by LukeOnuke** [comment]
I mean why not, just like not right at the top.

**Pull request merged**
